# Generated by Django 4.2.5 on 2025-05-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre de la intención (ej: 'saludo', 'despedida')", max_length=100, unique=True)),
                ('training_phrases', models.JSONField(default=list, help_text="Lista de frases de entrenamiento para el modelo NLP (ej: ['hola', 'buenos días'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Texto de respuesta del bot')),
                ('is_default', models.BooleanField(default=False, help_text='Si es True, se usará cuando no haya coincidencia exacta')),
                ('conditions', models.JSONField(blank=True, help_text='Condiciones contextuales en formato JSON (opcional)', null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot_management.intent')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
