# Generated by Django 4.2.5 on 2025-06-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0003_intent_description_intent_is_active_intent_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(help_text='Número de teléfono del usuario', max_length=20)),
                ('message', models.TextField(help_text='Mensaje recibido del usuario')),
                ('response', models.TextField(help_text='Respuesta generada por el bot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del mensaje')),
                ('intent', models.ForeignKey(blank=True, help_text='Intención detectada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_management.intent')),
            ],
        ),
    ]
